{% set name = "amp-rsl-rl" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amp_rsl_rl-{{ version }}.tar.gz
  sha256: 350eaf8c10c698f012c7c0f293d5b8715f9bc7ea67551e1fcd6647bba954f8ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=7.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - scipy >=1.7.0
    - pytorch >=1.10.0
    - rsl-rl-lib >=2.3.0

test:
  imports:
    - amp_rsl_rl
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ami-iit/amp-rsl-rl
  summary: Adversarial Motion Prior (AMP) reinforcement learning extension for PPO based on RSL-RL.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GiulioRomualdi
    - Giulero
    - traversaro
